### PR TITLE
fixed typo in winning probability in glossary

### PR DESCRIPTION
**Pull request by abhconcordium**
From memory, this should be `1-(1-f)^a`, not `1-(1-f)a`.

Could someone verify?

### CODE REVIEW

**Comment by abhconcordium** [comment]
@limemloh I wasn't sure if there was a proper way of doing exponentiation in this file format

**Comment by limemloh** [comment]
> @limemloh I wasn't sure if there was a proper way of doing exponentiation in this file format

We can enable a plugin to allow math in the form of latex expressions, but if this is the only place, then just use the `html` directive.

**Review by abizjak — CHANGES_REQUESTED** [review]
Good catch, but can you please make it pretty as well (with the exponential).

**Comment by abhconcordium** [comment]
> Good catch, but can you please make it pretty as well (with the exponential).

Latest push renders like this

image

**Review by limemloh — APPROVED** [review]

**Comment by limemloh** [comment]
@abhconcordium 
Because of the recent changes, you should also fix this in the `testnet4` branch

**Pull request merged**
