### PR TITLE
Reflect refactor of add -> name

### PR DESCRIPTION
**Pull request by abhconcordium**
update documentation to reflect refactor of config account add to config account name, as well as the name parameter not being optional.

### CODE REVIEW

**Comment by abhconcordium** [comment]
Tied to CB-990

**Review by limemloh — APPROVED** [review]

**Comment by abhconcordium** [comment]
After discussion with @limemloh, set as draft to avoid merging into external documentation, while feature is still internal only.

**Comment by abizjak** [comment]
We need to remember that this is incompatible with the latest released version, so we must not deploy this version onto the website.

**Comment by limemloh** [comment]
Now that only the `testnet4` branch is deployed, this should be safe to merge into `main`

**Pull request merged**
